@id=62cd5be74a0e789e3813e2fa
@host=http://localhost:3000


GET {{host}}

### Create a new user
POST {{host}}/users
Content-Type:application/json

   {"_id": 101,
    "name": {
        "title": "Ms",
        "first": "Liesje",
        "last": "Smal"
      },
      "username":"smal42",
      "email": "liesje.smal@example.com",
      "picture":"https://images.unsplash.com/photo-1633332755192-727a05c4013d?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=880&q=80",
      "Age": 42,
      "City": "San Diego",
      "Description": "Liesje has worked in the technology and association space for 15 years. He is the CEO and President of MemberClicks, an all-in-one membership management software company, and has helped them grow from just under 300 customers in 2004 to 3,000 today across North America"
    }

### Get all users
GET {{host}}/users

### Get one specific user by id
GET {{host}}/user/{{id}}

### Patch one specific user
PATCH {{host}}/user/{{id}}
Content-Type:application/json

{
   "key":"Age",
   "value":"99"
}

### UPDATE one specific user
PUT {{host}}/{{id}}
Content-Type:application/json

   {"_id": 101,
    "name": {
        "title": "Ms",
        "first": "Liesje",
        "last": "Smal"
      },
      "username":"smal42444",
      "email": "liesje.smal@example.com",
      "picture":"https://images.unsplash.com/photo-1633332755192-727a05c4013d?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=880&q=80",
      "Age": 42,
      "City": "San Diego",
      "Description": "Liesje has worked in the technology and association space for 15 years. He is the CEO and President of MemberClicks, an all-in-one membership management software company, and has helped them grow from just under 300 customers in 2004 to 3,000 today across North America"
    }


### Delete one specific user
DELETE {{host}}/users/{{id}}

